package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FullBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FullBuild")) {
    triggers {
        remove {
            vcs {
                branchFilter = "+:*"
            }
        }
    }

    features {
        add {
            commitStatusPublisher {
                publisher = gitlab {
                    gitlabApiUrl = "https://gitlab.com/api/v4"
                    accessToken = "credentialsJSON:271c5ea5-69f0-4bc8-854f-413abaaa29ed"
                }
            }
        }
    }
}
