package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.YouTrackIssueTracker
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.youtrack
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        remove {
            youtrack {
                id = "PROJECT_EXT_4"
                displayName = "YouTrack"
                host = "https://j.njsm.de/youtrack"
                userName = ""
                password = ""
                projectExtIds = "ML"
                accessToken = "credentialsJSON:94939717-d1c5-4b83-9d0f-52d919a3de6a"
                authType = YouTrackIssueTracker.AuthType.TOKEN
            }
        }
    }
}
